### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-html-atom-and-basic-elements-JmL5o8#1]
@egillespie Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-html-atom-and-basic-elements-JmL5o8/) and meets the following criteria:

- [x] Each of the following elements is used appropriately, at least once: `h1`, `h2`, `p`, `img`, `li`, `a`
- [x] At least one of the following elements is used: `ol`, `ul`
- [x] At least one external image is used and links to the page it came from

I used 4 spaces I'll fix it if anyone complains though

**Comment by egillespie** [comment]
I don't mind the 4 spaces. This project was supposed to be a resume for a fictional character, but you've met the criteria and then some so we can ship it. :shipit:

The title of the project usually has information about what to do with your code. Missing it isn't a big deal, if anything, we're not drawing enough attention to the title. I'll mention it to the team and see how we can give it better visibility. If you have any suggestions, please send them our way!

**Comment by lordcrekit** [comment]
It was? Was that in the project description? I must have totally missed it.
I'll fix it for the next project.

**Comment by egillespie** [comment]
:+1:
